### ISSUE TITLE
Make "blank page" coding possible

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/openethnographer-for-drupal#68]
When coding a post that has already been coded by someone else, currently we see all annotations that have ever been made on the post. There should be the possibility to toggle their visualization, because people might want to do their coding without being too influenced by other researchers, and also to remove visual clutter.

**Comment by tanius** [comment]
I think this is meant for the Discourse version of Open Ethnographer instead, so I have transferred it to there ([edgeryders/discourse #112](https://github.com/edgeryders/discourse/issues/112)). Closing here.
